[build]
  command = "npm run build && npm run deploy"
  publish = "dist"
  environment = [
    "OPENAI_API_KEY",
    "CLOUDFLARE_API_TOKEN"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
